In [42]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 美國教育資料庫

In [43]:
df = pd.read_csv("states.csv")

In [44]:
df

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_TRF,GRADES_8_TRF,GRADES_12_TRF,GRADES_1_8_TRF,GRADES_9_12_TRF,GRADES_ALL_TRF,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,NaN,NaN,NaN,NaN,NaN,NaN,208.327876,252.187522,207.963517,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.859712
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,NaN,NaN,NaN,NaN,NaN,NaN,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,NaN,NaN,NaN,NaN,NaN,NaN,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,NaN,NaN,NaN,NaN,NaN,NaN,208.398961,260.892247,196.764414,NaN
5,1992_COLORADO,COLORADO,1992,NaN,3185173.0,163253.0,1307986.0,1713934.0,3264826.0,1642466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,221.023429,272.398433,213.480890,266.419687
6,1992_CONNECTICUT,CONNECTICUT,1992,NaN,3834302.0,143542.0,1342539.0,2348221.0,3721338.0,2148041.0,...,NaN,NaN,NaN,NaN,NaN,NaN,226.798480,273.739345,222.417599,264.713904
7,1992_DELAWARE,DELAWARE,1992,NaN,645233.0,45945.0,420942.0,178346.0,638784.0,372722.0,...,NaN,NaN,NaN,NaN,NaN,NaN,217.899972,262.868585,206.389052,261.577921
8,1992_DISTRICT_OF_COLUMBIA,DISTRICT_OF_COLUMBIA,1992,NaN,709480.0,64749.0,0.0,644731.0,742893.0,329160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,192.600553,234.924621,178.557612,265.976765
9,1992_FLORIDA,FLORIDA,1992,NaN,11506299.0,788420.0,5683949.0,5033930.0,11305642.0,5166374.0,...,NaN,NaN,NaN,NaN,NaN,NaN,213.689751,259.908848,204.882606,262.118986
10,1992_GEORGIA,GEORGIA,1992,NaN,5536901.0,398701.0,2798674.0,2339526.0,5535942.0,3043984.0,...,NaN,NaN,NaN,NaN,NaN,NaN,215.594906,259.359434,206.844175,NaN
11,1992_HAWAII,HAWAII,1992,NaN,996809.0,71273.0,903443.0,22093.0,1040121.0,536115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,214.056666,257.410887,200.880272,NaN
12,1992_IDAHO,IDAHO,1992,NaN,859329.0,69138.0,531912.0,258279.0,886161.0,473505.0,...,NaN,NaN,NaN,NaN,NaN,NaN,221.562534,275.090294,NaN,NaN
13,1992_ILLINOIS,ILLINOIS,1992,NaN,9748650.0,597077.0,3073178.0,6078395.0,9850560.0,5010400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1992_INDIANA,INDIANA,1992,NaN,5060274.0,257044.0,2578149.0,2225081.0,5182754.0,2598925.0,...,NaN,NaN,NaN,NaN,NaN,NaN,221.037742,270.098944,219.763258,NaN
15,1992_IOWA,IOWA,1992,NaN,2663934.0,125665.0,1176205.0,1362064.0,2795774.0,1446478.0,...,NaN,NaN,NaN,NaN,NaN,NaN,229.884078,283.360009,222.852939,NaN
16,1992_KANSAS,KANSAS,1992,NaN,2245348.0,121625.0,903199.0,1220524.0,2234915.0,1165749.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1992_KENTUCKY,KENTUCKY,1992,NaN,2642902.0,289902.0,1643109.0,709891.0,2518082.0,1343438.0,...,NaN,NaN,NaN,NaN,NaN,NaN,215.048158,262.241282,211.562307,NaN
18,1992_LOUISIANA,LOUISIANA,1992,NaN,3341253.0,367822.0,1848734.0,1124697.0,3362853.0,1888349.0,...,NaN,NaN,NaN,NaN,NaN,NaN,204.140211,249.983926,196.762268,NaN
19,1992_MAINE,MAINE,1992,NaN,1206819.0,73160.0,511654.0,622005.0,1228869.0,685350.0,...,NaN,NaN,NaN,NaN,NaN,NaN,231.638840,278.635384,228.380027,NaN
20,1992_MARYLAND,MARYLAND,1992,NaN,4658498.0,228336.0,1778834.0,2651328.0,4698374.0,2628891.0,...,NaN,NaN,NaN,NaN,NaN,NaN,217.317708,264.825493,209.645497,NaN
21,1992_MASSACHUSETTS,MASSACHUSETTS,1992,NaN,5517659.0,273946.0,1439051.0,3804662.0,5245560.0,2751871.0,...,NaN,NaN,NaN,NaN,NaN,NaN,226.597918,272.783201,223.160076,NaN
22,1992_MICHIGAN,MICHIGAN,1992,NaN,9963137.0,537917.0,2539380.0,6885840.0,10170688.0,4681327.0,...,NaN,NaN,NaN,NaN,NaN,NaN,219.878352,267.353194,NaN,NaN
23,1992_MINNESOTA,MINNESOTA,1992,NaN,4684684.0,194092.0,2380754.0,2109838.0,4981125.0,2534882.0,...,NaN,NaN,NaN,NaN,NaN,NaN,228.493596,282.392205,218.301709,NaN
24,1992_MISSISSIPPI,MISSISSIPPI,1992,NaN,1684706.0,277706.0,901199.0,505801.0,1691990.0,956104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,201.828261,246.458035,201.529328,NaN
25,1992_MISSOURI,MISSOURI,1992,NaN,4043682.0,255194.0,1903124.0,1885364.0,4197600.0,2168135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,222.215600,271.131545,216.898079,NaN
26,1992_MONTANA,MONTANA,1992,NaN,828983.0,69947.0,337455.0,421581.0,781009.0,412219.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.301419,NaN
27,1992_NEBRASKA,NEBRASKA,1992,NaN,1542413.0,85423.0,492256.0,964734.0,1534046.0,909159.0,...,NaN,NaN,NaN,NaN,NaN,NaN,225.332648,277.654523,220.034963,NaN
28,1992_NEVADA,NEVADA,1992,NaN,1097076.0,45018.0,724032.0,328026.0,1251651.0,572623.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1992_NEW_HAMPSHIRE,NEW_HAMPSHIRE,1992,NaN,1063391.0,31020.0,86296.0,946075.0,1066647.0,581123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,229.664564,278.216326,223.466140,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,2017_MASSACHUSETTS,MASSACHUSETTS,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,249.102674,297.042225,235.699697,267.250533
1463,2017_MICHIGAN,MICHIGAN,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,235.555473,279.505455,217.753242,277.782589
1464,2017_MINNESOTA,MINNESOTA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,248.804303,293.962376,224.538513,265.468928
1465,2017_MISSISSIPPI,MISSISSIPPI,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,234.694193,270.914908,215.203306,268.616822
1466,2017_MISSOURI,MISSOURI,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,239.502289,280.596022,222.681081,256.344701
1467,2017_MONTANA,MONTANA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.721634,285.600437,222.326722,266.035007
1468,2017_NEBRASKA,NEBRASKA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,245.590675,288.405955,224.096225,267.208219
1469,2017_NEVADA,NEVADA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,231.685162,275.365456,214.841696,268.528555
1470,2017_NEW_HAMPSHIRE,NEW_HAMPSHIRE,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,245.319839,293.290654,228.900649,259.806407
1471,2017_NEW_JERSEY,NEW_JERSEY,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,247.855231,291.698552,232.943318,274.786040
1472,2017_NEW_MEXICO,NEW_MEXICO,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,229.704282,269.374084,207.704354,275.044552
1473,2017_NEW_YORK,NEW_YORK,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,235.548457,281.688000,221.884015,255.578543
1474,2017_NORTH_CAROLINA,NORTH_CAROLINA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.951393,281.926028,223.930906,264.157584
1475,2017_NORTH_DAKOTA,NORTH_DAKOTA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,244.243515,288.172322,221.519266,262.720477
1476,2017_OHIO,OHIO,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.928372,287.714266,225.261138,265.081922
1477,2017_OKLAHOMA,OKLAHOMA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,237.326270,274.688883,216.587775,268.450642
1478,2017_OREGON,OREGON,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,233.132460,282.173028,217.531073,261.236934
1479,2017_PENNSYLVANIA,PENNSYLVANIA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,241.672327,286.393832,224.924702,266.216684
1480,2017_RHODE_ISLAND,RHODE_ISLAND,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,237.554934,277.180126,223.353443,269.553823
1481,2017_SOUTH_CAROLINA,SOUTH_CAROLINA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,234.043993,274.673821,213.127835,265.767860
1482,2017_SOUTH_DAKOTA,SOUTH_DAKOTA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,241.588947,286.376160,221.750123,259.753002
1483,2017_TENNESSEE,TENNESSEE,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,236.692515,278.777735,218.952797,267.355727
1484,2017_TEXAS,TEXAS,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.943671,282.320510,214.878493,262.046853
1485,2017_UTAH,UTAH,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,242.480766,286.816559,225.159173,260.342577
1486,2017_VERMONT,VERMONT,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.893297,287.623388,226.445343,268.752420
1487,2017_VIRGINIA,VIRGINIA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,248.041059,290.081407,227.598382,273.402640
1488,2017_WASHINGTON,WASHINGTON,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,241.701001,289.131257,223.123409,267.744778
1489,2017_WEST_VIRGINIA,WEST_VIRGINIA,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,236.057019,273.415854,217.316396,271.617023
1490,2017_WISCONSIN,WISCONSIN,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,240.389213,288.143144,219.612694,258.700304
1491,2017_WYOMING,WYOMING,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,247.820619,288.761812,226.831211,269.371456

In [45]:
df.columns

Index(['PRIMARY_KEY', 'STATE', 'YEAR', 'ENROLL', 'TOTAL_REVENUE',
       'FEDERAL_REVENUE', 'STATE_REVENUE', 'LOCAL_REVENUE',
       'TOTAL_EXPENDITURE', 'INSTRUCTION_EXPENDITURE',
       ...
       'GRADES_4_TRF', 'GRADES_8_TRF', 'GRADES_12_TRF', 'GRADES_1_8_TRF',
       'GRADES_9_12_TRF', 'GRADES_ALL_TRF', 'AVG_MATH_4_SCORE',
       'AVG_MATH_8_SCORE', 'AVG_READING_4_SCORE', 'AVG_READING_8_SCORE'],
      dtype='object', length=193)

## 加州 8 年級學生數學程度
探討加州學生歷年數學程度

In [46]:
df_math = df[["STATE","YEAR","AVG_MATH_8_SCORE"]]

In [47]:
df_math.sort_values(by = ["AVG_MATH_8_SCORE"], ascending= False, inplace= True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [48]:
df_math.index= range(1,len(df_math)+1)

In [65]:
df_CAmath = df_math.drop(df_math[df_math.STATE!= "CALIFORNIA"].index)

In [66]:
df_CAmathNEW

           STATE  YEAR  AVG_MATH_8_SCORE
345   CALIFORNIA  2017        276.638200
353   CALIFORNIA  2013        275.901351
363   CALIFORNIA  2015        275.324573
398   CALIFORNIA  2011        272.769803
427   CALIFORNIA  2009        270.448588
429   CALIFORNIA  2007        270.381784
446   CALIFORNIA  2005        268.558129
461   CALIFORNIA  2003        267.049501
491   CALIFORNIA  1996        262.772478
496   CALIFORNIA  2000        262.171027
504   CALIFORNIA  1992        260.892247
546   CALIFORNIA  1993               NaN
597   CALIFORNIA  1994               NaN
648   CALIFORNIA  1995               NaN
709   CALIFORNIA  1997               NaN
760   CALIFORNIA  1998               NaN
811   CALIFORNIA  1999               NaN
873   CALIFORNIA  2001               NaN
924   CALIFORNIA  2002               NaN
975   CALIFORNIA  2004               NaN
1026  CALIFORNIA  2006               NaN
1077  CALIFORNIA  2008               NaN
1131  CALIFORNIA  2010               NaN
1183  CALIFORNIA  2012               NaN
1234  CALIFORNIA  2014               NaN
1285  CALIFORNIA  2016               NaN

In [69]:
np.mean(df_CAmath.AVG_MATH_8_SCORE)

269.35524363566543

## 麻州 8 年級學生數學程度
探討麻州學生歷年數學程度

In [70]:
df1 = pd.read_csv("states.csv")

df1_math1 = df1[["STATE","YEAR","AVG_MATH_8_SCORE"]]
df1_math1.sort_values(by = ["AVG_MATH_8_SCORE"], ascending= False, inplace= True)
df1_math1.index= range(1,len(df1_math1)+1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [73]:
df1_MAmath = df1_math1.drop(df1_math1[df1_math1.STATE!= "MASSACHUSETTS"].index)

In [77]:
df1_MAmath

              STATE  YEAR  AVG_MATH_8_SCORE
1     MASSACHUSETTS  2013        300.568235
2     MASSACHUSETTS  2009        298.854347
3     MASSACHUSETTS  2011        298.512431
4     MASSACHUSETTS  2007        297.923344
5     MASSACHUSETTS  2017        297.042225
6     MASSACHUSETTS  2015        296.908571
32    MASSACHUSETTS  2005        291.513541
104   MASSACHUSETTS  2003        286.520694
199   MASSACHUSETTS  2000        283.123246
327   MASSACHUSETTS  1996        277.565642
397   MASSACHUSETTS  1992        272.783201
563   MASSACHUSETTS  1993               NaN
614   MASSACHUSETTS  1994               NaN
665   MASSACHUSETTS  1995               NaN
726   MASSACHUSETTS  1997               NaN
777   MASSACHUSETTS  1998               NaN
828   MASSACHUSETTS  1999               NaN
890   MASSACHUSETTS  2001               NaN
941   MASSACHUSETTS  2002               NaN
992   MASSACHUSETTS  2004               NaN
1043  MASSACHUSETTS  2006               NaN
1095  MASSACHUSETTS  2008               NaN
1149  MASSACHUSETTS  2010               NaN
1200  MASSACHUSETTS  2012               NaN
1251  MASSACHUSETTS  2014               NaN
1302  MASSACHUSETTS  2016               NaN

In [75]:
np.mean(df1_MAmath.AVG_MATH_8_SCORE)

291.0286798484591

### 小結
以麻州作為美東代表、加州作為美西代表， 麻州 8 年級學生的平均數學程度高於加州 8 年級學生